// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/archivement-manager/pkg/db/ent/general"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// General is the model entity for the General schema.
type General struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// GoodID holds the value of the "good_id" field.
	GoodID uuid.UUID `json:"good_id,omitempty"`
	// CoinTypeID holds the value of the "coin_type_id" field.
	CoinTypeID uuid.UUID `json:"coin_type_id,omitempty"`
	// TotalUnits holds the value of the "total_units" field.
	TotalUnits uint32 `json:"total_units,omitempty"`
	// SelfUnits holds the value of the "self_units" field.
	SelfUnits uint32 `json:"self_units,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount decimal.Decimal `json:"amount,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*General) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case general.FieldAmount:
			values[i] = new(decimal.Decimal)
		case general.FieldCreatedAt, general.FieldUpdatedAt, general.FieldDeletedAt, general.FieldTotalUnits, general.FieldSelfUnits:
			values[i] = new(sql.NullInt64)
		case general.FieldID, general.FieldAppID, general.FieldUserID, general.FieldGoodID, general.FieldCoinTypeID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type General", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the General fields.
func (ge *General) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case general.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ge.ID = *value
			}
		case general.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ge.CreatedAt = uint32(value.Int64)
			}
		case general.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ge.UpdatedAt = uint32(value.Int64)
			}
		case general.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ge.DeletedAt = uint32(value.Int64)
			}
		case general.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				ge.AppID = *value
			}
		case general.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ge.UserID = *value
			}
		case general.FieldGoodID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field good_id", values[i])
			} else if value != nil {
				ge.GoodID = *value
			}
		case general.FieldCoinTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field coin_type_id", values[i])
			} else if value != nil {
				ge.CoinTypeID = *value
			}
		case general.FieldTotalUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_units", values[i])
			} else if value.Valid {
				ge.TotalUnits = uint32(value.Int64)
			}
		case general.FieldSelfUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field self_units", values[i])
			} else if value.Valid {
				ge.SelfUnits = uint32(value.Int64)
			}
		case general.FieldAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value != nil {
				ge.Amount = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this General.
// Note that you need to call General.Unwrap() before calling this method if this General
// was returned from a transaction, and the transaction was committed or rolled back.
func (ge *General) Update() *GeneralUpdateOne {
	return (&GeneralClient{config: ge.config}).UpdateOne(ge)
}

// Unwrap unwraps the General entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ge *General) Unwrap() *General {
	tx, ok := ge.config.driver.(*txDriver)
	if !ok {
		panic("ent: General is not a transactional entity")
	}
	ge.config.driver = tx.drv
	return ge
}

// String implements the fmt.Stringer.
func (ge *General) String() string {
	var builder strings.Builder
	builder.WriteString("General(")
	builder.WriteString(fmt.Sprintf("id=%v", ge.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(fmt.Sprintf("%v", ge.CreatedAt))
	builder.WriteString(", updated_at=")
	builder.WriteString(fmt.Sprintf("%v", ge.UpdatedAt))
	builder.WriteString(", deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", ge.DeletedAt))
	builder.WriteString(", app_id=")
	builder.WriteString(fmt.Sprintf("%v", ge.AppID))
	builder.WriteString(", user_id=")
	builder.WriteString(fmt.Sprintf("%v", ge.UserID))
	builder.WriteString(", good_id=")
	builder.WriteString(fmt.Sprintf("%v", ge.GoodID))
	builder.WriteString(", coin_type_id=")
	builder.WriteString(fmt.Sprintf("%v", ge.CoinTypeID))
	builder.WriteString(", total_units=")
	builder.WriteString(fmt.Sprintf("%v", ge.TotalUnits))
	builder.WriteString(", self_units=")
	builder.WriteString(fmt.Sprintf("%v", ge.SelfUnits))
	builder.WriteString(", amount=")
	builder.WriteString(fmt.Sprintf("%v", ge.Amount))
	builder.WriteByte(')')
	return builder.String()
}

// Generals is a parsable slice of General.
type Generals []*General

func (ge Generals) config(cfg config) {
	for _i := range ge {
		ge[_i].config = cfg
	}
}
