apiVersion: v1
kind: ConfigMap
metadata:
  name: archivement-middleware-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "archivement-middleware.npool.top"
      http_port: 50370
      grpc_port: 50371
      healthz_port: 50372
      prometheus_port: 50373
      appid: "89089012783789789719823798127398"
      serviceid: "6161ecc0-0b2c-11ed-b571-72e9de4b20f6"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
